# This workflow to test EKS connections and deploy service in kubernetes cluster.

name: CI with Java Spring Boot repo, maven build tool, packaging & pushing as image to ECR, Testing

# Events
on:
  push:
    branches: [ qa ]
  pull_request:
    branches: [ qa ]
    types: [ opened, edited, reopened, closed ]

env:
  ENVIRONMENT: qa
  CONSUL_HOST: consul-server.default.svc.cluster.local
  CONSUL_PORT: 8500
  APM_URL: skywalking-oap.default.svc.cluster.local:11800
  SERVICE_CODE: documentation-service
  SWAGGER: http://dev-ingress-gateway.gaiansolutions.com/
  ARTIFACT_RETENTION_DAYS: 10
  NEXUS_REPO_URL: http://dev.nexus-lib.gaiansolutions.com:8081/repository/releases
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  BASE_URL: http://dev-ingress-gateway.gaiansolutions.com
  CODE_PATH: /home/runner/work/documentation-service/documentation-service

  #For BVT
  API_ENV: API_K8S

# Workflow defination
jobs:
  ########## job to build the package and deploy to sonar for code analysis
  Build:
    if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'edited'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow the checkout
        run: |
          git fetch --prune --unshallow --tags
          git tag --list

      - name: Generate Version
        id: version
        uses: sceccotti89/Github-Action-Versioning@v1.0.5

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          # distribution: 'zulu'

      # Step that does that actual cache save and restore
      - name: caching dependancies for subsequent runs
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Setup Gaian Nexus Repo credentials
        uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: |
            [{
              "id": "nexus",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            }]
          mirrors: |
            [{
              "id": "nexus",
              "name": "nexus",
              "mirrorOf": "nexus",
              "url": "${{ env.NEXUS_REPO_URL }}",
              "blocked": false
            }]

      - name: Run Unit Tests, publish coverage to Sonar
        run: mvn clean install sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.projectKey=${{env.SERVICE_CODE}}-qa -Dsonar.host.url=${{ secrets.SONAR_HOST }} -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dproject.version=${{ steps.version.outputs.version }}

  Build_Deploy:
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow the checkout
        run: |
          git fetch --prune --unshallow --tags
          git tag --list

      - name: Generate Version
        id: version
        uses: sceccotti89/Github-Action-Versioning@v1.0.5

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          # distribution: 'zulu'

      # Step that does that actual cache save and restore
      - name: caching dependancies for subsequent runs
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Setup Gaian Nexus Repo credentials
        uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: |
            [{
              "id": "nexus",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            }]
          mirrors: |
            [{
              "id": "nexus",
              "name": "nexus",
              "mirrorOf": "nexus",
              "url": "${{ env.NEXUS_REPO_URL }}",
              "blocked": false
            }]

      - name: Run Unit Tests, publish coverage to Sonar
        run: mvn clean install sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.projectKey=${{env.SERVICE_CODE}}-qa -Dsonar.host.url=${{ secrets.SONAR_HOST }} -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dproject.version=${{ steps.version.outputs.version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.EKS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.EKS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.EKS_KUBE_CONFIG }}

      - name: Docker Build, tag, push image to Amazon ECR, and deploy in EKS using kubernetes
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ENVIRONMENT }}
          IMAGE_TAG: ${{env.SERVICE_CODE}}-${{ github.sha }}
          C_HOST: ${{ env.CONSUL_HOST }}
          C_PORT: ${{ env.CONSUL_PORT }}
          APM_URL: ${{ env.APM_URL }}
        run: |
          # Build a docker container and
          # steps.version.outputs.version
          # push it to ECR so that it can
          # be deployed to ECS/EKS
          sed -i'' -e "s/\$consul_url/$C_HOST/g" -e "s/\$consul_port/$C_PORT/g" -e "s/ENVIRONMENT/$ECR_REPOSITORY/g" -e "s/\$apm_url/$APM_URL/g" docker/startup.sh
          cat docker/startup.sh | grep consul
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          ##### replacing image tag and registry inside deployment file
          sed -i'' -e "s/REG/$ECR_REGISTRY/g" -e "s/IMAGE/$ECR_REPOSITORY/g" -e "s/TAG/$IMAGE_TAG/g" kubernetes-files/deployment.yaml
          kubectl apply -f kubernetes-files/deployment.yaml
          kubectl apply -f kubernetes-files/istio-rules.yaml

      - name: Check pods after apply
        run: kubectl get pods
      
      - name: wait for swagger to up 
        uses: mydea/action-wait-for-api@v1
        with:
          url: "${{env.BASE_URL}}/${{env.SERVICE_CODE}}/swagger-ui.html"
          method: GET
          timeout: 120

  COE_ANALYSIS:
    needs:
      - Build_Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow the checkout
        run: |
          git fetch --prune --unshallow --tags
          git tag --list

      - name: Checkout COE repo
        uses: actions/checkout@v2
        with:
          repository: gaiangroup/gaian-test-automation
          token: '${{ secrets.GITACTIONS_PAT }}'
          ref: integration
          path: coe

      - name: Run COE Analysis Check & Publish to Portal
        run: |
          pwd
          cd coe/coe-analysis/
          npm i
          service_code=${{env.SERVICE_CODE}} build_version=${{ github.sha }} code_path=${{ env.CODE_PATH }} SwaggerURI=${{ env.SWAGGER }} node app.js

  BVT:
    runs-on: ubuntu-latest
    needs: Build_Deploy

    steps:
      - name: Checkout COE repo
        uses: actions/checkout@v2
        with:
          repository: gaiangroup/gaian-test-automation
          token: '${{ secrets.GITACTIONS_PAT }}'
          ref: integration
          path: coe

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run BVT & Publish to Portal
        run: |
          pwd
          cd coe/platform-automation
          npm i
          TEST_PARAM=${{ env.API_ENV }} npm test

      - name: Save Test Report as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: BVT_REPORT
          path: coe/platform-automation/reports/report/*
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
          if-no-files-found: error

  PERFORMANCE_TEST:
    runs-on: ubuntu-latest
    needs: BVT
    steps:
      - name: Checkout COE repo
        uses: actions/checkout@v2
        with:
          repository: gaiangroup/gaian-test-automation
          token: '${{ secrets.GITACTIONS_PAT }}'
          ref: integration
          path: coe

      - name: Jmeter test
        uses: rbhadti94/apache-jmeter-action@v0.3.2
        with:
          testFilePath: coe/Perf-Test/STF/STF_PERF_BENCHAMRKING_SCRIPT_k8s.jmx
          outputReportsFolder: reports/
          args: "-JURI=dev-ingress-gateway.gaiansolutions.com"

      - name: Get data from Skywalking
        run: curl -X POST "http://65.1.154.213:8080/skywalking/dump?serviceName=${{env.SERVICE_CODE}}"

      - name: Explore Reports
        run: |
          sudo cp jmeter_log.log reports/
          sudo cp reports/statistics.json coe/kpi-metrics
          ls -la reports/
          ls -la coe/kpi-metrics
          cat jmeter_log.log
      - name: Retain Jmeter Reports
        uses: actions/upload-artifact@v2
        with:
          name: Perf_Reports
          path: reports/
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
          if-no-files-found: error

      - name: Push load test run to kpi DB
        run: |
          cd coe/kpi-metrics
          npm i
          service_code=${{env.SERVICE_CODE}} build_version=${{ github.sha }} node send_Data.js
